In [ ]:
# default_exp housing_data_collection

# Scraping housing data

> Why py explored?

In [ ]:
#hide
from nbdev.showdoc import *

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('./data/neiberhood.txt',sep='\t', header=None)
df.columns = ['NbCodeName', 'NbName']
df

        NbCodeName                                 NbName
0          Blmngtn                    Bloomington Heights
1          Blueste                               Bluestem
2           BrDale                              Briardale
3          BrkSide                              Brookside
4          ClearCr                            Clear Creek
5          CollgCr                          College Creek
6          Crawfor                               Crawford
7          Edwards                                Edwards
8          Gilbert                                Gilbert
9           IDOTRR                 Iowa DOT and Rail Road
10         MeadowV                         Meadow Village
11         Mitchel                               Mitchell
12           Names                             North Ames
13         NoRidge                             Northridge
14         NPkVill                        Northpark Villa
15         NridgHt                     Northridge Heights
16          NWAmes                         Northwest Ames
17         OldTown                               Old Town
18           SWISU  South & West of Iowa State University
19          Sawyer                                 Sawyer
20         SawyerW                            Sawyer West
21         Somerst                               Somerset
22         StoneBr                            Stone Brook
23          Timber                             Timberland
24         Veenker                                Veenker

In [ ]:
df.to_csv('./data/nbh.csv', index=False)

In [ ]:
# Ames city, Iowa

In [ ]:
[x + ', Ames city, Iowa, US' for x in list(df['NbName'])]

['Bloomington Heights, Ames city, Iowa, US',
 'Bluestem, Ames city, Iowa, US',
 'Briardale, Ames city, Iowa, US',
 'Brookside, Ames city, Iowa, US',
 'Clear Creek, Ames city, Iowa, US',
 'College Creek, Ames city, Iowa, US',
 'Crawford, Ames city, Iowa, US',
 'Edwards, Ames city, Iowa, US',
 'Gilbert, Ames city, Iowa, US',
 'Iowa DOT and Rail Road, Ames city, Iowa, US',
 'Meadow Village, Ames city, Iowa, US',
 'Mitchell, Ames city, Iowa, US',
 'North Ames, Ames city, Iowa, US',
 'Northridge, Ames city, Iowa, US',
 'Northpark Villa, Ames city, Iowa, US',
 'Northridge Heights, Ames city, Iowa, US',
 'Northwest Ames, Ames city, Iowa, US',
 'Old Town, Ames city, Iowa, US',
 'South & West of Iowa State University, Ames city, Iowa, US',
 'Sawyer, Ames city, Iowa, US',
 'Sawyer West, Ames city, Iowa, US',
 'Somerset, Ames city, Iowa, US',
 'Stone Brook, Ames city, Iowa, US',
 'Timberland, Ames city, Iowa, US',
 'Veenker, Ames city, Iowa, US']

In [ ]:
import googlemaps
from datetime import datetime

# gmaps = googlemaps.Client(key='Add Your Key here')

# # Geocoding an address
# geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')